name: Release

on:
  push:
    tags:
      - '*'
jobs:
  create-release:
    name: Create GH Release
    runs-on: ubuntu-latest
    steps:
      - run: gh release create ${{ github.ref }} --generate-notes
  build-and-upload:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            artifact_name: pcapdump
            asset_name: pcapdump-darwin-aarch64
          - target: aarch64-unknown-linux-gnu
            artifact_name: pcapdump
            asset_name: pcapdump-linux-aarch64
    runs-on: ubuntu-latest
    name: build and upload release
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo build --release
      - name: Upload
        run: |
          cp ./${{ matrix.artifact_name}} ./${{ matrix.asset_name}}
          gh release upload ${{ github.ref }}
        working-directory: target/release ${{ matrix.asset_name}}