name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '*'
jobs:
  create-release:
    name: Create GH Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh release create ${{ github.ref_name }} --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
  build-and-upload:
    needs:
      - create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-11
            target: aarch64-apple-darwin
            artifact_name: pcapdump
            asset_name: pcapdump-darwin-aarch64
            cross: true
          - target: aarch64-unknown-linux-gnu
            artifact_name: pcapdump
            asset_name: pcapdump-linux-aarch64
            cross: true
    runs-on: ubuntu-latest
    name: build and upload release
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross compiler
        if: ${{ matrix.cross }}
        run: cargo install cross

      - run: cross build --release --target ${{ matrix.target }}
        if: ${{ matrix.cross }}

      - run: cargo build --release --target ${{ matrix.target }}
        if: ${{ !matrix.cross }}

      - name: Upload
        run: |
          cp ${{ matrix.artifact_name}} ${{ matrix.asset_name}}
          gh release upload ${{ github.ref_name }} ${{ matrix.asset_name}}
        working-directory: target/release
        env:
          GH_TOKEN: ${{ github.token }}